version: '3.8'

services:
  custom-postgres:
    image: postgres
    container_name: social-app-postgres
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=social_app
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db:
